image: debian/stable
# the busybox grep doesn't have the --files-with-matches
# image: alpine/edge
secrets:
- 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
sources:
- git+ssh://git@git.sr.ht/~aaronkelly/aaronpkelly.github.io
tasks:
- push-to-github: |-
    echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    cd aaronpkelly.github.io
    git checkout master
    ./generateIndexAndPostsList.sh markdown go
    git add .
    git commit -m 'adding generated files'
    git remote set-url origin git@github.com:aaronpkelly/aaronpkelly.github.io
    git push -u origin master