image: alpine/edge
secrets:
  - 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
  - 03f64564-69d2-4a5c-8cb9-e5c7ad610cfc
sources:
  - git@git.sr.ht/~aaronkelly/aaronpkelly.github.io
tasks:
  - push-to-github: |
      cd aaronpkelly.github.io
      git checkout master
      git remote set-url origin https://aaronpkelly:$GITHUB_PASS@github.com/USERNAME/REPOSITORY.git
      git push