image: alpine/edge
secrets:
  - 03f64564-69d2-4a5c-8cb9-e5c7ad610cfc
  - cc91d33a-6642-46d7-89d3-fb94afcaecec
sources:
  - git@git.sr.ht/~aaronkelly/aaronpkelly.github.io
tasks:
  - push-to-github: |
      cd aaronpkelly.github.io
      echo "$GITHUB_PASS"
      cat ~/GITHUB_PASS
      git remote set-url origin https://aaronpkelly:$GITHUB_PASS@github.com/USERNAME/REPOSITORY.git
      git push