image: alpine/edge
secrets:
  - 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
  - cc91d33a-6642-46d7-89d3-fb94afcaecec
sources:
  - git@git.sr.ht/~aaronkelly/aaronpkelly.github.io
tasks:
  - push-to-github: |
      git remote -v