#!/user/bin/env bash

VLCPATH="/c/Program Files/VideoLAN/VLC"

mkdir listened

# -I null: start as background task (currently disabled)
# --intf dummy: no GUI (currently disabled)
# --play-and-exit: quits vlc after each audio file
for file in *.mp3; do
	echo "Now playing: $file"
	"$VLCPATH"/vlc.exe --play-and-exit --qt-start-minimized "$file"
	mv "$file" listened
done
