#!/bin/bash

packages=$(whiptail --title "cafe install v0.1" --checklist \
"choose all options to perform" 60 60 40 \
"git" "git" ON \
"libcurl3" "curl" ON \
"mc" "midnight commander" ON \
"moc" "moc (music on command-line)" ON \
"tmux" "tmux" ON \
"tree" "tree (needed for password manager)" ON \
"vim" "vim" ON 3>&1 1>&2 2>&3)
 
exitstatus=$?
if [ $exitstatus = 0 ]; then
	echo "installing: " $packages

	arr=($packages)
	for e in "${arr[@]}"
		do
			noParen="$(echo $e | sed 's/"//g')"
			echo "now installing: " $e
			sudo apt-get install "$noParen"
		done
else
	echo "You chose Cancel."
fi

packages=$(whiptail --title "cafe install v0.1" --checklist \
"choose all options to perform" 60 60 40 \
"git" "git" ON \
"libcurl3" "curl" ON \
"mc" "midnight commander" ON \
"moc" "moc (music on command-line)" ON \
"tmux" "tmux" ON \
"tree" "tree (needed for password manager)" ON \
"vim" "vim" ON 3>&1 1>&2 2>&3)
 
exitstatus=$?
if [ $exitstatus = 0 ]; then
	echo "installing: " $packages

	arr=($packages)
	for e in "${arr[@]}"
		do
			noParen="$(echo $e | sed 's/"//g')"
			echo "now installing: " $e
			sudo apt-get install "$noParen"
		done
else
	echo "You chose Cancel."
fi
